[final_columns_order]
titulo = 0
numero_expediente = 1
tipo_contrato = 2
estado_licitacion = 3
importe_licitacion = 4
valor_estimado_contrato = 5
fecha_limite_presentacion = 6
organo_contratacion = 7
enlace = 8
codigo_cpv = 9
procedimiento_contratacion = 10
forma_presentacion = 11
duracion_contrato = 12
financiacion_ue = 13
fecha_formalizacion = 14
lugar_ejecucion = 15
sistema_contratacion = 16
tramitacion = 17
descripcion = 18
# Esta columna siempre dejarla con el indice mayor
pdf = 19
importe_con_iva = 20

[final_columns_order_st]
numero_expediente = 0
codigo_cpv = 1
estado_licitacion = 2
fecha_limite_presentacion = 3
resumen_breve = 4
importe_licitacion = 5
importe_con_iva = 6
valor_estimado_contrato = 7
titulo = 8
organo_contratacion = 9
tipo_contrato = 10
lugar_ejecucion = 11
duracion_contrato = 12
financiacion_ue = 13
forma_presentacion = 14
clasificacion = 15
fuente = 16
enlace = 17
pdf = 18
fecha_proceso = 19


[final_columns_st]
Nº Expediente = 0
Código CPV = 1
Estado = 2
Fecha Límite Presentación = 3
Resumen breve = 4
Importe (€) = 5
Importe con IVA (€) = 6
Valor estimado contrato (€) = 7
Título = 8
Órgano de contratación = 9
Tipo de contrato = 10
Lugar de ejecución = 11
Duración del contrato = 12
Financiación UE = 13
Forma de presentación = 14
Clasificación = 15
Fuente = 16
URL = 17
PDF / Ruta = 18
Fecha de ejecución del proceso = 19

[filter_columns_app]
Estado = 0
Importe (€) = 1
Valor estimado contrato (€) = 2
Fecha Límite Presentación = 3
Forma de presentación = 6
Nº Expediente = 7
Lugar de ejecución  = 8
Tipo de contrato = 9
Órgano de contratación = 10
Fuente = 12
Clasificación = 13


[and_columns_order]
titulo_de_expediente = 0
numero_de_expediente = 1
tipo_de_contrato = 2
estado = 3
importe_de_licitacion_sin_iva = 4
importe_de_licitacion_con_iva = 20
valor_estimado = 5
fecha_fin_de_presentacion = 6
organo_de_contratacion = 7
url = 8
clasificacion_cpv = 9
procedimiento = 10
forma_de_presentacion = 11
duracion_del_contrato = 12
lugar_de_ejecucion = 15
sistema_de_racionalizacion = 16
tramitacion = 17
descripcion = 18
pdf_prescripciones_tecnicas = 19


[esp_columns_order]
descripcion = 0
numero_expediente = 1
tipo_contrato = 2
estado_de_la_licitacion = 3
presupuesto_base_de_licitacion_sin_impuestos = 4
presupuesto_base_de_licitacion_con_impuestos = 20
valor_estimado_del_contrato = 5
fecha_fin_de_presentacion_de_oferta = 6
organo_de_contratacion = 7
enlace = 8
codigo_cpv = 9
procedimiento_de_contratacion = 10
metodo_de_presentacion_de_la_oferta = 11
financiacion_ue = 13
lugar_de_ejecucion = 15
sistema_de_contratacion = 16
tipo_de_tramitacion = 17
objeto_del_contrato = 18
pdf_pliego_prescripciones_tecnicas = 19

[eus_columns_order]
titulo = 0
codigo_expediente = 1
tipo_de_contrato = 2
estado_de_la_tramitacion = 3
presupuesto_del_contrato_sin_iva = 4
poder_adjudicador = 7
enlace_detalle = 8
sistema_de_contratacion = 16
objeto_del_contrato = 18
pdf_prescripciones_tecnicas = 19


[mad_columns_order]
titulo = 0
numero_de_expediente = 1
tipo_de_contrato = 2
situacion = 3
presupuesto_base_licitacion_sin_impuestos = 4
presupuesto_base_licitacion_importe_total = 20
valor_estimado_sin_impuestos = 5
fecha_y_hora_limite_de_presentacion_de_ofertas_o_solicitudes_de_participacion = 6
enlace_detalle = 8
codigo_cpv = 9
procedimiento_de_adjudicacion = 10
metodo_de_presentacion_de_ofertas = 11
duracion_del_contrato = 12
financiacion_de_la_union_europea = 13
sistema_de_contratacion = 16
tipo_de_tramitacion = 17
objeto_del_contrato = 18
pdf_prescripciones_tecnicas = 19
